model:
  type: SEGSID
  kwargs:
    pd_a: 5
    pd_b: 2
    pd_pad: 0
    R3: True
    R3_T: 8
    R3_p: 0.16
    in_ch: 1
    bsn_base_ch: 128
    bsn_num_module: 9
    is_refine: True
    sematic_type: ResNet

model_input: [noisy] # e.g.) real_noisy, syn_noisy, clean
model_type: only_denoise

trainer: Trainer
training:
  dataset: prep_KLSG_Train
  dataset_args:
    add_noise: None # e.g.) None bypass uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
    crop_size: [160, 160]
    aug: ['hflip', 'rot']
    n_repeat: 1
  
  batch_size: 8
  max_epoch: 128

  init_lr: 2e-4
  scheduler:
    type: Cosine
    min: 5e-7

  loss: 1*self_L1
  tmp_info: []
  optimizer:
    type: Adam
    Adam:
      betas: [0.9, 0.999]

  warmup: True  # default False
  warmup_iter: 200

validation:
  dataset: KLSG_Test

  dataset_args:
    crop_size: None # [64, 64]
    add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
    n_data: None

  crop: 160
  add_con: 0.5
  floor: True

  val: True
  save_image: True

  start_epoch: 64
  interval_epoch: 64

checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 10

test:
  dataset: KLSG_Test
  crop: 160

  dataset_args:
    crop_size: None # [64, 64]
    add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.

  add_con: 0.5
  floor: True

  save_image: True
